token: "kIWC67smb8Ysmxwj_Q1XaqWA4ciNQw2F"
botGame: "Rixa 3.0 beta | Hosted by Mister_Fix"
shards: 5

botAdmins:
- "104695503358291968"

sqlCredentials:
  hostName: "localhost"
  databaseName: "rixa"
  userName: "root"
  password: ""
  port: "3306"
